openapi: "3.1.0"
info:
  title: "currency convertor API"
  description: "currency convertor API"
  version: "1.0.0"
servers:
  - url: "https://currency convertor"
paths:
  /currencies:
    get:
      summary: Get a list of all currencies
      operationId: getCurrencies
      tags:
        - Currencies
      responses:
        '200':
          description: A list of currencies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currencies'
        '500':
          description: Internal server error


components:
  schemas:
    User:
      type: object
      required:
        - id
        - firstName
        - lastName
        - email
      properties:
        id:
          type: string
          example: "12345"
        firstName:
          type: string
          example: "John"
        lastName:
          type: string
          example: "Doe"
        email:
          type: string
          format: email
          example: "john.doe@example.com"
        phone:
          type: string
          example: "+1-555-1234"
        role:
          type: string
          enum:
            - admin
            - user
            - manager
          example: "user"

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

security:
  - ApiKeyAuth: []

tags:
  - name: Users
    description: Operations related to user management